### ISSUE TITLE
Vote for Distribution API

### ISSUE THREAD

**Issue by Otodontidae** [ccideas/sbom-utilities-pipe#8]
Would love to have to tie to Dependency Track and be able to block the pipeline if the analysis fails on DT

**Comment by ccideas** [comment]
Thanks for the suggestion @Otodontidae. Integrating Dependency Track is near the top of the roadmap. I will keep you up to date with its progress.

**Comment by ccideas** [comment]
Hey @Otodontidae 

Support to send a SBOM to a downstream Dependency Track server has been added as of the 1.5.0 release. 

`
- step:
      name: Process sBOM
      script:
        # the build directory is owned by root but the pipe runs as the bitbucket-user
        # change the permission to allow the pipe to write to the build directory
        - chmod 777 build
        - pipe: docker://ccideas/sbom-utilities-pipe:1.5.0
          variables:
            SEND_SBOM_TO_DTRACK: 'true'
            DTRACK_URL: ${DTRACK_URL}
            DTRACK_PROJECT_ID: ${DTRACK_PROJECT_ID}
            DTRACK_API_KEY: ${DTRACK_API_KEY}
`

This initial implementation uses the /v1/bom PUT API to send a single SBOM via a Project ID & Team API Key

If you have any feedback or issues with this implementation please let me know & open a new issue on the project. Closing this for now
